misc improvements: nimble test; doAssert defined cpp
kaushalmodi/std_vector pull request #8
Opened 2020-06-08 01:19 UTC by timotheecour

* IIRC this used to not work `static: doAssert defined(cpp)` but I fixed it in some recent PR
* `task test` helps for later inclusion in important_packages

2020-06-09 11:30 UTC, kaushalmodi requested changes

2020-06-09 11:30 UTC, kaushalmodi commented on std_vector.nimble
> +template echoRun(cmd) =
Can this template and task live in config.nims instead? I follow a convention to use the .nimble only for the package metadata.

2020-06-09 18:01 UTC, kaushalmodi commented on src/std_vector.nim
> +static: doAssert defined(cpp)
Sorry, but I still prefer this 1-line user-error instead of a multi-line backtrace that doAssert would provide.

2020-06-09 18:10 UTC, kaushalmodi commented on std_vector.nimble
> +template echoRun(cmd) =
I already have a `test` task in my global config.nims. Can I instead call this in important packages if this gets added there? https://github.com/kaushalmodi/std_vector/blob/834b962c5f9dc5f872285c855ae658995211476f/.travis.yml#L42-L43

2020-06-10 02:31 UTC, timotheecour commented on src/std_vector.nim
> +static: doAssert defined(cpp)
done, changed to `when not defined(cpp)` which IIRC used to not work but now works

2020-06-10 02:44 UTC, timotheecour commented on std_vector.nimble
> +template echoRun(cmd) =
found another way: `nimble test` automatically runs tests in `tests/`

2020-06-10 02:45 UTC, timotheecour commented
PTAL

2020-06-10 03:59 UTC, merged